algo = input('Digite algo: ')
print('O tipo primitivo desse valor é:', type(algo))
print('É um número? Resposta: {}.'.format(algo.isnumeric()))
print('É alfabético?', algo.isalpha())
print('É alfanumérico?', algo.isalnum())
print('É ASCII?', algo.isascii())
print('É um dígito?', algo.isdigit())
print('É número decimal?', algo.isdecimal())
print('Está em minúsculo?', algo.islower())
print('Está em maiúsculo?', algo.isupper())
print('Só tem espaço?', algo.isspace())
print('É um identificador?', algo.isidentifier())
print('É imprimível?', algo.isprintable())
print('Está capitalizado?', algo.istitle())
